In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sqlite3

conn = sqlite3.connect("Medigreen.db")
c = conn.cursor()

In [6]:
q = """
    select * from dispensaryhasproduct as dhp
    
"""

df = pd.read_sql(q, conn)
df.groupby("date")['productID'].mean()

date
2018-06-26 22:05:11.964586      78.962963
2018-06-26 22:05:15.030543     448.194828
2018-06-26 22:05:21.234396      78.962963
2018-06-26 22:05:23.798336     448.194828
2018-06-26 22:05:28.962015     820.643979
2018-06-26 22:05:31.726263    1017.109524
2018-06-26 22:05:34.645300    1152.100000
2018-06-26 22:05:35.334934    1190.692308
2018-06-26 22:05:36.128873    1242.664634
2018-06-26 22:05:38.256989    1371.554455
2018-06-26 22:05:39.569408    1266.544118
2018-06-26 22:05:40.524679    1518.488372
2018-06-26 22:05:41.566393    1641.532164
2018-06-26 22:05:43.963840    1665.732955
2018-06-26 22:05:46.224144    1846.769231
2018-06-26 22:05:48.283857    1921.518072
2018-06-26 22:05:49.594941    1994.873874
2018-06-26 22:05:51.288698    2063.123077
2018-06-26 22:05:52.288612    2092.340426
2018-06-26 22:05:53.733589    2035.744681
2018-06-26 22:05:54.462366    2020.944444
2018-06-26 22:05:55.256915    2441.795833
2018-06-26 22:05:58.625499    2510.532895
2018-06-26 22:06:00.620808    2160.713115
2018-06-26 22:06:02.366877    2469.800000
2018-06-26 22:06:03.305550    2771.736364
2018-06-26 22:06:05.161335    2832.803030
2018-06-26 22:06:06.831411    3031.500000
2018-06-26 22:06:07.379893    2364.500000
2018-06-26 22:06:07.952815    2771.736364
                                 ...
2018-06-28 08:17:37.359511    3773.574803
2018-06-28 08:17:38.722454    4247.000000
2018-06-28 08:17:39.264536    2725.168317
2018-06-28 08:17:40.386378    6963.574074
2018-06-28 08:17:41.438300    6448.128655
2018-06-28 08:17:43.152803    6403.069364
2018-06-28 08:17:45.372867    1152.100000
2018-06-28 08:17:46.107058    2060.451613
2018-06-28 08:17:47.302653    5868.659091
2018-06-28 08:17:48.046129    5398.704545
2018-06-28 08:17:49.041506    3265.625000
2018-06-28 08:17:49.972035    6745.370370
2018-06-28 08:17:51.576971    4621.606383
2018-06-28 08:17:53.117744    3124.742424
2018-06-28 08:17:53.986857    7397.152542
2018-06-28 08:17:54.919568    5654.088889
2018-06-28 08:17:55.836733    3016.193878
2018-06-28 08:17:57.891009    6874.000000
2018-06-28 08:17:58.850466    3996.385965
2018-06-28 08:18:00.213585    1916.513889
2018-06-28 08:18:01.688334    5123.000000
2018-06-28 08:18:02.057733    6701.807018
2018-06-28 08:18:02.969842    6701.807018
2018-06-28 08:18:03.997289    5910.392857
2018-06-28 08:18:06.429261    5661.626556
2018-06-28 08:18:08.785984    7319.368421
2018-06-28 08:18:09.346429    3773.574803
2018-06-28 08:18:10.819458    3852.022727
2018-06-28 08:18:12.306833    5661.626556
2018-06-28 08:18:14.960641    6012.050955
Name: productID, Length: 277, dtype: float64